version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo npm install hexo-cli -g
      - run: yarn install
      - run: hexo g
      - run: git config --global user.name "zhiqiang du"
      - run: git config --global user.email "haxck.x@gmail.com"
      - run: hexo d
      
      
    filters:
      branches:
        only: hexo
