version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install hexo-cli -g
      - run: yarn install
      - run: hexo g
      - run: hexo d
      
    filters:
      branches:
        only: master
