menu:
  Home: /
  Archives: /archives
  About: https://haxck.com/about
  Portfolio: https://haxck.com/portfolio/

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: false 
disqus_shortname: 

# LiveRe comment
liveRe: true

# google analytics
googleTrackId: UA-93076840-1 
